name: CI Build

on: push
#push:
  #branches:
    #- uos

#pull_request:
  #branches:
    #- uos

jobs:
  archlinux:
    name: Archlinux Build Check
    runs-on: ubuntu-latest
    container: docker.io/library/archlinux:latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Refresh pacman repository
        run: pacman -Syy
      #- name: Install build dependencies
        #run: pacman -S --noconfirm base-devel cmake ninja qt5-tools deepin-qt-dbus-factory dtkwidget
      - name: Install boost
        run: pacman -S --noconfirm extra/boost git openssh
      - name: Show boost
        run: |
          ls /usr/lib/libboost_*
          ls /usr/include/boost
      - name: Show Current Path
        run: |
          mkdir -p include/boost
          mkdir -p lib
          cp -rf /usr/lib/libboost_* lib 
          cp -rf /usr/include/boost include/boost
  
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3 # 使用第三方 Action 把构建完成的 Artifact 部署到指定分支
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main        
          
