name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Install boost
      run: |
        sudo -E apt-get install libboost-all-dev``
    
    - name: Show boost library
      run: |
        sudo -E ls /usr/lib/libboost_*
        sudo -E ls /usr/include/boost
    
    - name: Show Current Path
      run: |
        sudo -E pwd
        
