name: CI Build

on: push

jobs:
  archlinux:
    name: Archlinux Build Check
    runs-on: ubuntu-latest
    #container: docker.io/library/archlinux:latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Pull Archlinux
        run: |
          sudo -E apt update
          sudo -E apt upgrade
          sudo -E curl -fsSL https://get.docker.com -o get-docker.sh
          sudo -E sudo sh get-docker.sh
          sudo -E dockerd > /tmp/docker.log 2>&1 &
          sudo -E docker pull archlinux


