name: CI Build

on: push

jobs:
  archlinux:
    name: Archlinux Build Check
    runs-on: ubuntu-latest
    #container: docker.io/library/archlinux:latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Update Ubuntu
        run: |
          sudo -E apt update
          #sudo -E apt upgrade
          sudo -E apt install git

      - name: Install Docker
        run: |
          sudo -E curl -fsSL https://get.docker.com -o get-docker.sh
          sudo -E sudo sh get-docker.sh

      - name: Pull Archlinux
        run: |
          sudo -E dockerd > /tmp/docker.log 2>&1 &
          sudo -E docker pull archlinux

      - name: Docker Test
        run: |
          sudo -E docker run -i archlinux /bin/bash
          pacman --noconfirm -Syyu
          pacman -S --noconfirm extra/boost
          ls /usr/lib/libboost_*
          ls /usr/include/boost
          ls -al
          pwd
          exit

      - name: Localhost Test
        run: |
          sudo -E ls -al
          sudo -E pwd


