name: Remote SSH
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ arch.IP }}
        username: ${{ arch.USER }}
        password: ${{ arch.PRIVATE_KEY }}
        port: ${{ arch.PORT }}
        script: |
          cd Repository

          ${{ secrets.SCRIPT}}
          pm2 restart 0
