name: CI Build

on: push
#push:
  #branches:
    #- uos

#pull_request:
  #branches:
    #- uos

jobs:
  archlinux:
    name: Archlinux Build Check
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          #port: ${{ secrets.PORT }}
          script: whoami

